spring:
  security:
    user:
      name: admin
      password: admin123

  datasource:
    url: jdbc:postgresql://localhost:5432/tooldb
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: bhatkarthik93@gmail.com
    password: ptmkxtdbppsdcavb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

jwt:
  secret: mysecretkey