spring:
  security:
    user:
      name: ${APP_USER:admin}
      password: ${APP_PASSWORD:admin123}

  datasource:
    url: jdbc:postgresql://localhost:5432/tooldb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}